libbpf: add an ability to delete qdisc via bpf_tc_hook_destroy from C++
bpf_tc_hook_destroy() deletes qdisc only if hook.attach_point is set to
BPF_TC_INGRESS | BPF_TC_EGRESS, but it is impossible to do from C++ code
because hook.attach_point is enum, but it is prohibited to set struct
enum member to non-enum value in C++.

This patch introduces new enum value BPF_TC_BOTH = BPF_TC_INGRESS | BPF_TC_EGRESS
This value allows to delete qdisc from C++ code.

An example of program compatible with C but incompatible with C++:
\#include <bpf/libbpf.h>
int main() {
    struct bpf_tc_hook hook;
    hook.attach_point = BPF_TC_INGRESS | BPF_TC_EGRESS;
}

'clang program.c' is OK, but 'clang++ program.cpp' fails:
program.cpp:4:40: error: assigning to 'enum bpf_tc_attach_point' from incompatible type 'int'
    4 |     hook.attach_point = BPF_TC_INGRESS | BPF_TC_EGRESS;
      |                         ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
1 error generated.

The same issue with g++.

Signed-off-by: Sergey V. Lobanov <sergey@lobanov.in>